# This file is part of SoSy-Lab Common,
# a library of useful utilities:
# https://github.com/sosy-lab/java-common-lib
#
# SPDX-FileCopyrightText: 2007-2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

language: java
jdk:
  - openjdk11
addons:
  apt:
    packages:
      - jq
env:
  - NAME='Unit Tests'
before_install: # lets update the very old version of ANT in TravisCI
  - wget --no-check-certificate https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.5-bin.tar.bz2
  - tar -xvf apache-ant-1.10.5-bin.tar.bz2
  - export PATH=`pwd`/apache-ant-1.10.5/bin:$PATH
  - echo $(ant -version)
install:
  - ant resolve-dependencies
script:
  - ant unit-tests-coverage
matrix:
  include:
    - env: NAME='Build with ECJ'
      script:
        - ant build-project-ecj
    - env: NAME='Create Javadoc' GH_REF='github.com/sosy-lab/common-java.git'
      script:
        - ant javadoc collect-options
    - env: NAME=Checkstyle
      script:
        - ant run-checkstyle -Dcheckstyle.output=plain && cat Checkstyle*.xml && [ $(cat Checkstyle*.xml | grep -vic audit) -eq 0 ]
    - env: NAME=SpotBugs
      script:
        - ant run-spotbugs -Dspotbugs.output=text && cat SpotBugs.xml && test \! -s SpotBugs.xml
    - env: NAME='Check source-code format'
      script:
        - ant format-source && git diff -s --exit-code
deploy:
  - skip_cleanup: true
    provider: script
    script: build/deploy-gh-pages.sh
    on:
      condition: $NAME = "Create Javadoc"
  - skip_cleanup: true
    provider: script
    script: build/deploy-coverage.sh
    on:
      jdk: openjdk8
      condition: $NAME = "Unit Tests"
notifications:
  email:
    - common-java-dev@googlegroups.com
git:
  depth: 1
cache:
  directories:
  - $HOME/.ivy2
